### ISSUE TITLE
Fancier version of Lovers and Rivals

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#28]
A fancier version of Lovers and Rivals that uses jquery, require, etc.

**Comment by mkremins** [comment]
I don't think we actually want to do this anymore! We removed RequireJS from the project entirely, and we've been generally trying to develop smaller and cleaner example projects overall, since people get lost very easily in the bigger and more complicated ones. If anything, we might want to try _simplifying_ the existing version of _Lovers and Rivals_.
